---
  - hosts: GoldenWasteWebApp
    vars:
    - jarName: ROOT.jar
    - jarRemotePath: /home/tomcat

    tasks:
    - name: GET/DOWNLOAD jar file from S3 bucket
      amazon.aws.aws_s3:
        profile: personal
        bucket: devopsjunction
        mode: get
        object: "ROOT.jar"
        dest: "{{ jarRemotePath }}/{{ jarName }}"
      register: getresult

    - debug:
        msg="{{ getresult.msg }}"
      when: getresult.changed
      
    - name: get current date
      set_fact: bkpdate="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

    - name: create directory with a date in name
      file: path="/home/tomcat/{{ bkpdate }}"
            state=directory
            mode=0755

    - name: backup jar
      shell: "cp /usr/local/tomcat/webapps/{{ jarName }} /home/tomcat/{{ bkpdate }}/"
      
    - name: Unzip JAR file
      unarchive: src={{ jarRemotePath }}/{{ jarName }} dest=/usr/local/tomcat/webapps/ROOT/ copy=no mode=0755 owner=tomcat9 group=tomcat9
      notify:
          - restart tomcat9
    
    - name: Delete remote jar file
      file: path={{ jarRemotePath }}/{{ jarName }} state=absent
      
    - name: wait for tomcat to start
      wait_for: port=8080 timeout=60
      
    handlers:
      - name: Restart tomcat9
        service: name=tomcat9 state=restarted