---
  - hosts: GoldenWasteDB
    become: yes
    vars:
      new_mysql_root_password: DevOps@2022
      mysqlsoftware:
        - mysql-server
        - mysql-client

    tasks:
      - name: install python, pip etc
        shell: apt-get -y install "{{ item }}"
        with_items:
          - python3-pip
          - python3-dev
          - default-libmysqlclient-dev
          - build-essential

      - name: Install MySQL server
        shell: apt-get -y install mysql-server

      - name: Install MySQL client
        shell: apt-get -y install mysql-client

      - name: pip install mysqlclient
        shell: pip install mysqlclient

      - name: Start the MySQL service
        action: service name=mysql state=started

      - name: copy .my.cnf file with root password credentials
        template: src=/home/ubuntu/GoldenWaste/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

      - name: update mysql root password for all root accounts
        mysql_user:
          name: root
          host: "{{ item }}"
          password: "{{ new_mysql_root_password }}"
        with_items:
          - "{{ ansible_hostname }}"
          - 127.0.0.1
          - ::1
          - localhost

      - name: delete anonymous MySQL server user for localhost
        action: mysql_user user="" state="absent"

      - name: remove the MySQL test database
        action: mysql_db db=test state=absent

      - name: Remove   /root/.my.cnf
        ansible.builtin.file:
          path: /root/.my.cnf
          state: absent