---
  - hosts: GoldenWasteWebApp
    gather_facts: false
    tasks:
      - name: Install Maven
        become: yes
        apt:
          name: maven
          state: present
          update_cache: yes