---
  - hosts: GoldenWasteWebApp
    tasks:
      - name: Install Maven and Git
        become: yes
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
            - maven
            - git

      - name: Clone a github repository
        git:
          repo: https://github.com/MohanadSinan/goldenwaste-sda-hackathon.git
          dest: /home/ubuntu/GoldenWaste
          clone: yes
          update: yes