---
  - hosts: GoldenWasteWebApp
    gather_facts: false
    tasks:
      - name: Install Maven
        become: yes
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
            - maven